---
- name: Configure | haproxy | pidfile
  lineinfile:
    state: present
    dest: /etc/init.d/haproxy
    regexp: '^PIDFILE='
    line: "PIDFILE={{ haproxy_pidfile_path }}"
  notify: Reload Service | haproxy
  tags:
    - pidfile
    - service
