---
- name: Generate Locale | en_CA.UTF-8
  locale_gen:
    state: present
    name: en_CA.UTF-8
  tags:
     - localization

- name: Generate Locale | fr_CA.UTF-8
  locale_gen:
    state: present
    name: fr_CA.UTF-8
  tags:
     - localization
